services:
    php:
        container_name: php
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 80:80
        volumes:
            - .:/var/www/html/

    mysql:
        container_name: mysql
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: 'testdb'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
        volumes:
            - mysqldata:/var/lib/mysql

    phpmyadmin:
        container_name: pma
        image: phpmyadmin
        restart: always
        ports:
            - 3000:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            
volumes:
    mysqldata:
